# Generated by Django 5.1 on 2024-08-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.IntegerField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalidade.participante')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalidade.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPersonalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.FloatField(default=0)),
                ('conscienciosidade', models.FloatField(default=0)),
                ('extroversao', models.FloatField(default=0)),
                ('amabilidade', models.FloatField(default=0)),
                ('neuroticismo', models.FloatField(default=0)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personalidade.participante')),
            ],
        ),
    ]
